# Standards: 0.1
---
- name: Fact alfred user
  set_fact:
    alfred_user: "{{ alfred_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - alfred

- become: "{{ (alfred_user != ansible_user_id) | bool }}"
  become_user: "{{ alfred_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: alfred
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - alfred

- name: Remove quarantine flag
  register: alfred_quarantine
  failed_when: alfred_quarantine.rc != 0 and "No such xattr" not in alfred_quarantine.stderr
  changed_when: alfred_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Alfred\ 4.app
  tags:
    - alfred

...
