# Standards: 0.1
---
- name: Kill alfred
  command: killall Alfred\ 4
  register: alfred_kill
  failed_when: alfred_kill.rc != 0 and "No matching processes belonging to you were found" not in alfred_kill.stderr
  become: "{{ (alfred_user != ansible_user_id) | bool }}"
  become_user: "{{ alfred_user }}"

- name: Start alfred
  when: alfred_started
  command: open -j /Applications/Alfred\ 4.app
  become: "{{ (alfred_user != ansible_user_id) | bool }}"
  become_user: "{{ alfred_user }}"

...
